### PR TITLE
Added method to support Echo framework.

### PR DESCRIPTION
**Pull request by kewlburn**
In order to register this package to Echo custom validator I need to add new method to validate struct.

Feel free to delete this PR if this is not applicable. Thanks!

### CODE REVIEW

**Comment by syssam** [comment]
I think it will be better, please change the pr.
example: https://github.com/syssam/go-validator/tree/master/examples/gin
<pre>
// file echo_validator.go
package main

import (
	"sync"

	validator "github.com/syssam/go-validator"
)

// DefaultValidator struct
type DefaultValidator struct {
	once     sync.Once
	validate *validator.Validator
}

// Validate return error
func (v *DefaultValidator) Validate(obj interface{}) error {
	v.lazyinit()
	if err := validator.ValidateStruct(obj); err != nil {
		return error(err)
	}
	return nil
}

func (v *DefaultValidator) lazyinit() {
	v.once.Do(func() {
		v.validate = validator.New()
	})
}
</pre>
<pre>
// file main.go
e := echo.New()
e.Validator = &DefaultValidator{}
</pre>

**Comment by kewlburn** [comment]
In that case I removed the new method I created before. 

By the way thanks for the package. This is simpler than the other existing validators.

**Comment by syssam** [comment]
@kewlburn thanks.
I just want to create a simple validator for the project.
However, this package is not stable, still developing, so use carefully.
when stabled, I will release a tag.

**Comment by kewlburn** [comment]
@syssam awesome! thank you!

**Pull request merged**
